# Change these first
owner: mabreyes # Your GitHub organization or username, where this repository lives
repo: status.marcreyes.xyz # The name of this repository

sites:
  - name: Main website
    url: https://marcreyes.ph
    icon: https://cdn-static-s3.marcreyes.xyz/assets/marcreyesph/images/ico/favicon.ico
  - name: Blog (Medium)
    url: https://blog.marcreyes.ph
    icon: https://cdn-static-s3.marcreyes.xyz/assets/marcreyesph/images/ico/favicon.ico
  - name: DEV
    url: https://dev.marcreyes.ph
    icon: https://cdn-static-s3.marcreyes.xyz/assets/marcreyesph/images/ico/favicon.ico
  - name: XYZ
    url: https://marcreyes.xyz
    icon: https://cdn-static-s3.marcreyes.xyz/assets/marcreyesph/images/ico/favicon.ico
  - name: URL shortener (Rebrandly)
    url: https://marcrey.es
    icon: https://cdn-static-s3.marcreyes.xyz/assets/marcreyesph/images/ico/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.marcreyes.xyz
  favicon: https://cdn-static-s3.marcreyes.xyz/assets/marcreyesph/images/ico/favicon.ico
  # baseUrl: /your-repo-name
  logoUrl: https://cdn-static-s3.marcreyes.xyz/assets/marcreyesph/images/marc-memoji.png
  name: Status
  introTitle: "Status is an uptime monitoring for all services deployed by Marc Reyes."
  introMessage: For inquiries, send an e-mail to [webadmin@marcreyes.ph](mailto:webadmin@marcreyes.ph).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
